image: node:10

stages:
  - install
  - test
  - build

install:
  stage: install
  tags:
    - shared
  script:
    - npm install
  artifacts:
    expire_in: 30 mins
    paths:
      - node_modules/

lint:
  stage: test
  script:
    - npm run -s lint
  dependencies:
    - install

flow:
  stage: test
  script:
    - npm run -s flow
  dependencies:
    - install

test:
  stage: test
  script:
    - npm run -s test
  dependencies:
    - install
  coverage: /All files\s*\|\s*([\d\.]+)/
  artifacts:
    paths:
    - test/results/

mutate:
  stage: test
  script:
    - npm install
    - npm run -s test:mutate
  artifacts:
    paths:
    - test/results

build:
  stage: build
  script:
    - npm run -s build
  dependencies:
    - install
